name: terraform-plan

description: |
  This action is usually run on Pull Request creation and updates.
  It is a pipeline to run `terraform plan`.
  It includes an optional validation step using several static code analyzers.

inputs:

  backend:
    description: Terraform backend configuration file (default is none)
    required: false

  github-token:
    description: |
      Optional GitHub Token when elevated permissions are needed
      that cannot be provided by the default token (default is `github.token`)
    required: false
    default: ${{ github.token }}

  run-terraform-validate:
    description: |
      Before running `terraform plan`, do a static code analysis by running `terraform-validate`
    default: 'true'
    required: false

  terraform-version:
    description: Terraform version (default is 'latest')
    default: latest
    required: false

  working-directory:
    description: Directory containing the Terraform module code. (default = ".")
    default: '.'
    required: false

  workspace:
    description: Terraform workspace
    default: 'default'
    required: false

runs:

  using: composite

  steps:
    - name: prepare
      id: prepare
      shell: bash
      run: |
        # create artifacts directory
        mkdir -p .artifacts

    - name: setup-terraform
      id: setup-terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false
        terraform_version: ${{ inputs.terraform-version }}

    - name: init
      id: init
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      working-directory: ${{ inputs.working-directory }}
      run: |
        backend=${{ inputs.backend }}

        if [ -z "${backend}"]; then
          terraform init -input=false -upgrade
        else
          terraform init -input=false -upgrade -backend-config="${backend}"
        fi

    - name: "select-workspace: ${{ inputs.workspace }}"
      id: select-workspace
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: terraform workspace select ${{ inputs.workspace }} || terraform workspace new ${{ inputs.workspace }}

    - name: terraform-validate
      id: terraform-validate
      if: ${{ inputs.run-terraform-validate == 'true' }}
      uses: mjheitland/github-actions/terraform-validate@v1
      with:
        github-token: ${{ inputs.github-token }}
        terraform-version: ${{ inputs.terraform-version }}

    - name: terraform-plan
      id: terraform-plan
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        terraform plan -no-color -input=false -lock=false -out .artifacts/terraform.plan
        terraform show -no-color .artifacts/terraform.plan > .artifacts/terraform-plan.txt
        ls -al .artifacts
      continue-on-error: true

    - name: post-comments
      if: |
        github.event_name == 'pull_request' ||
        github.event_name == 'pull_request_target'
      uses: actions/github-script@v6
      env:
        PLAN: "terraform\n${{ steps.terraform-plan.outputs.stdout }}"
      with:
        script: |
          const output = `#### Terraform Initialization \`${{ steps.init.outcome }}\`
          #### Terraform Validation \`${{ steps.terraform-validate.outcome }}\`
          #### Terraform Plan \`${{ steps.terraform-plan.outcome }}\`
          <details><summary>Show Plan</summary>
          \`\`\`bash\n
          ${process.env.PLAN}
          \`\`\`
          </details>
          *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
          await github.rest.issues.createComment({
            issue_number: context.payload.pull_request.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })

    - name: publish-artifact
      id: publish-artifact
      uses: actions/upload-artifact@v3
      with:
        name: plan-artifacts
        path: .artifacts

    - name: exit-on-error
      id: exit-on-error
      shell: bash
      if: |
        steps.terraform-plan.outcome == 'failure'
      run: |
        printf 'ERROR - One or more steps failed in this pipeline.\n'
        printf 'Results:\n'
        printf 'Step "plan"             : %s\n' "${{ steps.terraform-plan.outcome }}"
        exit 1
