name: terraform-apply

description: |
  Action to run terraform apply for a root module based on an existing Terraform plan file.

inputs:

  backend:
    description: Terraform backend configuration file (default is none)
    required: false

  github-token:
    description: |
      Optional GitHub Token when elevated permissions are needed
      that cannot be provided by the default token (default is `github.token`)
    required: false
    default: ${{ github.token }}

  plan-file:
    description: Path to the Terraform plan file
    default: .artifacts/terraform.plan
    required: false

  working-directory:
    description: Directory containing the Terraform module code. (default = ".")
    default: '.'
    required: false

  workspace:
    description: Terraform workspace
    default: 'default'
    required: false

runs:
  using: composite
  steps:
    - name: prepare
      id: prepare
      shell: bash
      run: |
        # create artifacts directory
        # (won't be changed if it already exists from a previous run of `terraform-plan`)
        mkdir -p .artifacts

    - name: setup-terraform
      id: setup-terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false
        terraform_version: ${{ inputs.terraform-version }}

    - name: init
      id: init
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      working-directory: ${{ inputs.working-directory }}
      run: |
        backend=${{ inputs.backend }}

        if [ -z "${backend}"]; then
          terraform init -input=false -upgrade
        else
          terraform init -input=false -upgrade -backend-config="${backend}"
        fi

    - name: "select-workspace: ${{ inputs.workspace }}"
      id: select-workspace
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: terraform workspace select ${{ inputs.workspace }} || terraform workspace new ${{ inputs.workspace }}

    - name: apply
      id: apply
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        if [ ! -f "${{ inputs.plan-file }}" ]; then
          printf 'ERROR - File Not Found: %s. This action requires the Terraform plan file to be created first.' "${{ inputs.plan-file }}"
          exit 1
        fi

        terraform show -no-color ${{ inputs.plan-file }}
        terraform apply -no-color -auto-approve -input=false ${{ inputs.plan-file }} | tee .artifacts/terraform-apply.txt

    - name: output
      id: output
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        terraform output -json | \
          jq 'to_entries | map_values(.value + { key: .key }) | map(select(.sensitive | not)) | from_entries' \
          >.artifacts/output.json

    - name: publish
      id: publish
      uses: actions/upload-artifact@v3
      with:
        name: apply-artifacts
        path: .artifacts
